kind: pipeline
name: default

steps:
- name: test
  image: alpine:3.10.0
  commands:
  - apk add php7 php7-dom php7-xml php7-xmlwriter composer
  - composer install
  when:
    event:
    - push